services:
  jenkins:
    build: .
    container_name: crypto-jenkins
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      # Mount Docker socket for building images in pipeline
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins_home:
    driver: local
